### ISSUE TITLE
EFP 4.0 issue pistol ammo 5.7

### ISSUE THREAD

**Issue by Carnagehunts** [ahuyn/anomaly-ballistics#12]
[xray_pifen.log](https://github.com/ahuyn/anomaly-ballistics/files/11413716/xray_pifen.log)

!ERROR get_object_by_id | no game object recieved from id (35076)
! [LUA]  0 : [C  ] __index
! [LUA]  1 : [Lua] ...games/efpv4/bin/..\gamedata\scripts\arti_handlers.script(487) : ignite_npc
! [LUA]  2 : [Lua] ...games/efpv4/bin/..\gamedata\scripts\arti_handlers.script(571) : 
! [LUA]  3 : [Lua] ...ames/efpv4/bin/..\gamedata\scripts\ballistics_mcm.script(71) : on_before_hit
! [LUA]  4 : [Lua] ...ames/efpv4/bin/..\gamedata\scripts\ballistics_mcm.script(139) : 
! [LUA] SCRIPT RUNTIME ERROR
! [LUA]  0 : [C  ] __index
! [LUA]  1 : [Lua] ...games/efpv4/bin/..\gamedata\scripts\arti_handlers.script(487) : ignite_npc
! [LUA]  2 : [Lua] ...games/efpv4/bin/..\gamedata\scripts\arti_handlers.script(571) : 
! [LUA]  3 : [Lua] ...ames/efpv4/bin/..\gamedata\scripts\ballistics_mcm.script(71) : on_before_hit
! [LUA]  4 : [Lua] ...ames/efpv4/bin/..\gamedata\scripts\ballistics_mcm.script(139) : 
! [LUA] ...games/efpv4/bin/..\gamedata\scripts\arti_handlers.script:487: attempt to index local 'damage' (a number value)
! [LUA]  0 : [C  ] __index
! [LUA]  1 : [Lua] ...games/efpv4/bin/..\gamedata\scripts\arti_handlers.script(487) : ignite_npc
! [LUA]  2 : [Lua] ...games/efpv4/bin/..\gamedata\scripts\arti_handlers.script(571) : 
! [LUA]  3 : [Lua] ...ames/efpv4/bin/..\gamedata\scripts\ballistics_mcm.script(71) : on_before_hit
! [LUA]  4 : [Lua] ...ames/efpv4/bin/..\gamedata\scripts\ballistics_mcm.script(139) : 
! [SCRIPT ERROR]: ...games/efpv4/bin/..\gamedata\scripts\arti_handlers.script:487: attempt to index local 'damage' (a number value)
 
FATAL ERROR
 
[error]Expression    : <no expression>
[error]Function      : CScriptEngine::lua_pcall_failed
[error]File          : ..\xrServerEntities\script_engine.cpp
[error]Line          : 204
[error]Description   : fatal error
[error]Arguments     : LUA error: ...games/efpv4/bin/..\gamedata\scripts\arti_handlers.script:487: attempt to index local 'damage' (a number value)
 

stack trace:

**Comment by Carnagehunts** [comment]
Replicated with unstable core on zombies. Or any round that ignites on full auto or semi.

**Comment by ahuyn** [comment]
fixed while back
