### ISSUE TITLE
STALKER Anomaly icons messed up

### ISSUE THREAD

**Issue by The-Great-Assyr** [ahuyn/anomaly-ballistics#15]
Hello there and friendly greetings!
I've installed your addon on Stalker Anomaly (no big modpacks like gamma or efp) along other 250 addons. Your addon is the last one in the list so I guess it is the last one to be loaded.
Everything seems to go fine but when I open F7 menu in the Ammo section, the icons are totally jumbled up
https://cdn.discordapp.com/attachments/1065168136577482753/1124693330693984306/ss_user_07-01-23_15-16-50_k00_marsh.jpg
(_this is a screenshot of the grok's+arti addon for gamma but the jumbling of the icon is absolutely the same, also I am not using that mod, I have GBOOBs and your addon separated_).
Same thing when objects are spawned in the inventory.

Not sure if I messed up something or there is something else going on. Have you a suggestion about this, please?

**Comment by ahuyn** [comment]
Have any DLTX mods? Those can wreak havoc with the icon positioning. This mod has custom ammo icons so any more custom ammo icons on top is going to be a bad time.

**Comment by The-Great-Assyr** [comment]
Yes, I have a lot of dltx addons and some of them are ammo addons. I will check all of them to see what's the messy one. Thanks for the hint!
