### ISSUE TITLE
m79, rg6 fires only registered once

### ISSUE THREAD

**Issue by morobukan** [ahuyn/anomaly-ballistics#16]
greetings Author, i have this issue with grenade launcher m79 and rg6 fires only registered once, second fire and so on doesnt have effects on enemies, like nothing happened, the gun fires but thats it. does anomaly-ballistics also covered explosives? i played EFP 4.0 with latest anomaly-ballistics.

p.s. under barrel GL worked just fine.

**Comment by ahuyn** [comment]
Got a chance to look into this, I have a fix coming

**Comment by morobukan** [comment]
https://github.com/ahuyn/anomaly-ballistics/assets/125895276/e0847cac-b134-4745-a6ae-e5f7133ea428

i upload vid of it, hope itd help

**Comment by morobukan** [comment]
its fixed with the latest version! thank you!
